version: "3"

services:
  simulator:
    container_name: simulator
    image: golang:1.16
    working_dir: /src/simulator
    volumes:
      - ./:/src/simulator
    entrypoint: tail -f /dev/null
    networks:
      - workshop

networks:
  workshop:
    external: true
