version: "3"

services:
  server:
    container_name: server
    image: node
    working_dir: /src/ms_storage
    ports:
      - 3333:3333
    volumes:
      - ./:/src/ms_storage
    entrypoint: tail -f /dev/null
    networks:
      - workshop

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storage
    networks:
      - workshop

networks:
  workshop:
    external: true
