version: "3"

services:
  api:
    container_name: api
    image: node
    working_dir: /src/api
    volumes:
      - ./:/src/api
    ports:
      - 3001:3001
    tty: true
    entrypoint: tail -f /dev/null
    networks:
      - workshop

networks:
  workshop:
    external: true
